services:
  planti_db:
    image: mysql:8.4
    container_name: planti_db
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planti
      MYSQL_USER: admin
      MYSQL_PASSWORD: 9x*UwARA5@
    volumes:
      - planti_db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - planti_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  planti:
    container_name: planti
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      planti_db:
        condition: service_healthy
    networks:
      - planti_net

networks:
  planti_net:
    driver: bridge

volumes:
  planti_db_data:
